### ISSUE TITLE
Better documentation support

### ISSUE THREAD

**Issue by emgre** [stepfunc/oo_bindgen#14]
Documentation handling in the schema could be better.

- [ ] Actually validate all the symbol names referenced in the documentations. It is currently a TODO in the code: https://github.com/grid-io/oo_bindgen/blob/5149d529e383466b560fdca2f7a489ef9eb04af5/oo-bindgen/src/lib.rs#L466
- [ ] Offer to link to a method of a class and validate it. In the C generator, it can easily find the native function associated with that method.
- [ ] Offer to link with a struct element and validate it.
- [ ] Instead of relying on the `DocBuilder`, the `From<&str>` implementation could actually parse the string and resolve the links, warnings, etc.
- [ ] Make a difference between the `@brief` and the detailed description
- [ ] Implement proper linking in .NET and Java.

**Comment by jadamcrain** [comment]
Another thing that seems to come up as I write docs is what to name things...

For example, what name do you chose for an iterator argument?

In C, it's best to call it an `iterator` in the docs, but this doesn't translate well to Java/C#. It might be reasonable to have some "short codes" that lets the back-end substitute and appropriate name:

{iterator}:
`C: iterator`
`Java: List`
`C#: ICollection`
