### ISSUE TITLE
Calculate hash of API to detect changes that requires a semver minor update

### ISSUE THREAD

**Issue by emgre** [stepfunc/oo_bindgen#21]
By computing a hash based on all the native function names, their argument types, their return type and the struct fields, it would be possible to embed a unique hash in the generated FFI DLL. This hash would always be the same if only a patch update is required. If a function is modified or added, then the hash would be different and it would mean that at least a minor update is needed (or a major if the change is not backward-compatible).

For a formal description of semver, see https://semver.org/

**Comment by jadamcrain** [comment]
Been thinking more about this, and what we really want to be able to detect is *backwards* compatibility for the *minor* version number.  This will require more than just a running hash.
